default:
	pdflatex isogeometric-analysis.tex
	bibtex   isogeometric-analysis
	pdflatex isogeometric-analysis.tex
	pdflatex isogeometric-analysis.tex

talk:
	pdflatex isogeometric-analysis-talk.tex
	bibtex   isogeometric-analysis-talk
	pdflatex isogeometric-analysis-talk.tex
	pdflatex isogeometric-analysis-talk.tex

poster:
	pdflatex isogeometric-analysis-talk.tex

clean:
	rm *.aux *.out *.log *.blg *.bbl *.glo *.toc
