default:
	pdflatex isogeometric-analysis.tex
	bibtex   isogeometric-analysis
	pdflatex isogeometric-analysis.tex
	pdflatex isogeometric-analysis.tex

talk:
	pdflatex me7751-final-project-talk.tex
	bibtex   me7751-final-project-talk
	pdflatex me7751-final-project-talk.tex
	pdflatex me7751-final-project-talk.tex

poster:
	pdflatex isogeometric-analysis-talk.tex

clean:
	rm *.aux *.out *.log *.blg *.bbl *.glo *.toc
